# Generated by Django 6.0.3 on 2026-04-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da propriedade', max_length=70, verbose_name='Nome')),
                ('classificacao', models.BooleanField(default=False, help_text='Classificação da propriedade', verbose_name='Classificação')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='chale_comum',
            fields=[
                ('propriedade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'Chale comum',
                'verbose_name_plural': 'Chales comum',
            },
            bases=('propriedades.propriedade',),
        ),
        migrations.CreateModel(
            name='chale_exclusivo',
            fields=[
                ('propriedade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'Chale exclusivo',
                'verbose_name_plural': 'Chales exclusivos',
            },
            bases=('propriedades.propriedade',),
        ),
    ]
