# Generated by Django 4.2.30 on 2026-05-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da propriedade', max_length=70, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('CHALE_COMUM', 'Chalé Comum'), ('CHALE_EXCLUSIVO', 'Chalé Exclusivo'), ('PORTAO', 'Portão')], help_text='Tipo de propriedade', max_length=50, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='chale_comum',
            fields=[
                ('propriedade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'Chale comum',
                'verbose_name_plural': 'Chales comum',
            },
            bases=('propriedades.propriedade',),
        ),
        migrations.CreateModel(
            name='chale_exclusivo',
            fields=[
                ('propriedade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'Chale exclusivo',
                'verbose_name_plural': 'Chales exclusivos',
            },
            bases=('propriedades.propriedade',),
        ),
        migrations.CreateModel(
            name='Portao',
            fields=[
                ('propriedade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propriedades.propriedade')),
            ],
            options={
                'verbose_name': 'Portão',
                'verbose_name_plural': 'Portões',
            },
            bases=('propriedades.propriedade',),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='portao_associado',
            field=models.ForeignKey(blank=True, help_text='Portão associado a este chalé exclusivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chales_exclusivos', to='propriedades.portao', verbose_name='Portão Associado'),
        ),
        migrations.AddField(
            model_name='portao',
            name='propriedade_linkada',
            field=models.ForeignKey(blank=True, help_text='Propriedade na qual este portão está localizado', limit_choices_to=models.Q(('tipo', 'PORTAO'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portoes_linkados', to='propriedades.propriedade', verbose_name='Propriedade Linkada'),
        ),
    ]
