# Generated by Django 6.0.3 on 2026-07-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriedade',
            options={'ordering': ['nome'], 'verbose_name': 'Propriedade', 'verbose_name_plural': 'Propriedades'},
        ),
    ]
