# Generated by Django 6.0.3 on 2026-04-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='tipo',
            field=models.CharField(choices=[('propriedade', 'Propriedade'), ('chale_comum', 'Chale Comum'), ('chale_exclusivo', 'Chale Exclusivo')], default='propriedade', max_length=20, verbose_name='Tipo'),
        ),
    ]
