# Generated by Django 4.2.30 on 2026-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portao',
            name='propriedade_linkada',
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
