# Generated by Django 4.2.30 on 2026-05-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_remove_portao_propriedade_linkada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='portao_associado',
            field=models.ForeignKey(blank=True, help_text='Portão associado a este chalé exclusivo', limit_choices_to={'tipo': 'PORTAO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chales_exclusivos', to='propriedades.propriedade', verbose_name='Portão Associado'),
        ),
    ]
