# Generated by Django 6.0.3 on 2026-07-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do modelo da chave', max_length=70, verbose_name='Nome do modelo da chave')),
                ('propriedade', models.ForeignKey(help_text='Propriedade relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='chaves', to='propriedades.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(help_text='Código da cópia da chave', verbose_name='Código')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADA', 'Emprestada'), ('PERDIDA', 'Perdida')], default='DISPONIVEL', help_text='Status da cópia da chave', max_length=20, verbose_name='Status')),
                ('chave', models.ForeignKey(help_text='Chave relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='copias', to='chaves.chave', verbose_name='Chave')),
            ],
            options={
                'verbose_name': 'Cópia de Chave',
                'verbose_name_plural': 'Cópias de Chaves',
            },
        ),
    ]
