# Generated by Django 6.0.3 on 2026-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da chave', max_length=70, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(help_text='Código da cópia da chave', verbose_name='Código')),
                ('status', models.CharField(help_text='Status da cópia da chave', max_length=50, verbose_name='Status')),
                ('valor_restituicao', models.FloatField(help_text='Valor de restituição da cópia', verbose_name='Valor Restituição')),
            ],
            options={
                'verbose_name': 'Cópia de Chave',
                'verbose_name_plural': 'Cópias de Chaves',
            },
        ),
    ]
