# Generated by Django 4.2.30 on 2026-05-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiachave',
            name='valor_restituicao',
        ),
        migrations.AlterField(
            model_name='chave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='copiachave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
