# Generated by Django 6.0.3 on 2026-04-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.AlterField(
            model_name='chave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
