# Generated by Django 6.0.3 on 2026-07-03 20:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'ordering': ['propriedade__nome', 'nome'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.AlterModelOptions(
            name='copiachave',
            options={'ordering': ['chave__nome', 'codigo'], 'verbose_name': 'Cópia de Chave', 'verbose_name_plural': 'Cópias de Chaves'},
        ),
        migrations.AddField(
            model_name='copiachave',
            name='data_perda',
            field=models.DateField(blank=True, help_text='Data em que a cópia foi marcada como perdida', null=True, verbose_name='Data da perda'),
        ),
        migrations.AddField(
            model_name='copiachave',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações internas sobre esta cópia', verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='copiachave',
            name='valor_restituicao',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Valor cobrado caso esta cópia seja perdida', max_digits=8, verbose_name='Valor de restituição'),
        ),
        migrations.AlterField(
            model_name='copiachave',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADA', 'Emprestada'), ('PERDIDA', 'Perdida'), ('MANUTENCAO', 'Em manutenção'), ('INATIVA', 'Inativa')], default='DISPONIVEL', help_text='Status da cópia da chave', max_length=20, verbose_name='Status'),
        ),
    ]
