# Generated by Django 6.0.3 on 2026-04-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
        ('propriedades', '0002_propriedade_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='propriedade',
            field=models.ForeignKey(blank=True, help_text='Propriedade relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chaves', to='propriedades.propriedade', verbose_name='Propriedade'),
        ),
        migrations.AddField(
            model_name='copiachave',
            name='chave',
            field=models.ForeignKey(blank=True, help_text='Chave relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copias', to='chaves.chave', verbose_name='Chave'),
        ),
    ]
