# Generated by Django 6.0.3 on 2026-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_alter_chave_options_alter_copiachave_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copiachave',
            name='data_perda',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a cópia foi marcada como perdida', null=True, verbose_name='Data e hora da perda'),
        ),
    ]
