# Generated by Django 6.0.3 on 2026-04-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_chave_propriedade_copiachave_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(help_text='Nome do modelo da chave', max_length=70, verbose_name='Nome do modelo da chave'),
        ),
    ]
