# Generated by Django 6.0.3 on 2026-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cliente', max_length=70, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Telefone do cliente', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail do cliente', max_length=50, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
