# Generated by Django 6.0.3 on 2026-04-30 00:10

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='clientes', variations={}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='E-mail do cliente', max_length=50, unique=True, verbose_name='E-mail'),
        ),
    ]
