# Generated by Django 6.0.3 on 2026-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(help_text='Data da retirada do empréstimo', verbose_name='Data de Retirada')),
                ('data_prevista', models.DateField(help_text='Data prevista de devolução', verbose_name='Data Prevista')),
                ('data_devolucao', models.DateField(blank=True, help_text='Data da devolução do empréstimo', null=True, verbose_name='Data de Devolução')),
                ('multa', models.IntegerField(default=0, help_text='Multa por atraso', verbose_name='Multa')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
