# Generated by Django 6.0.3 on 2026-04-30 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
        ('clientes', '0001_initial'),
        ('propriedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(help_text='Data da retirada do empréstimo', verbose_name='Data de Retirada')),
                ('data_prevista', models.DateField(help_text='Data prevista de devolução', verbose_name='Data Prevista')),
                ('data_devolucao', models.DateField(blank=True, help_text='Data da devolução do empréstimo', null=True, verbose_name='Data de Devolução')),
                ('multa', models.IntegerField(default=0, help_text='Multa por atraso', verbose_name='Multa')),
                ('cliente', models.ForeignKey(blank=True, help_text='Nome do cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='clientes.cliente', verbose_name='Cliente')),
                ('copia', models.ForeignKey(blank=True, help_text='Cópia de chave relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='chaves.copiachave', verbose_name='Cópia')),
                ('propriedade', models.ForeignKey(blank=True, help_text='Propriedade do empréstimo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='propriedades.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
