# Generated by Django 4.2.30 on 2026-05-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(help_text='Data da retirada do empréstimo', verbose_name='Data de Retirada')),
                ('data_prevista', models.DateField(help_text='Data prevista de devolução', verbose_name='Data Prevista')),
                ('data_devolucao', models.DateField(blank=True, help_text='Data da devolução do empréstimo', null=True, verbose_name='Data de Devolução')),
                ('cliente', models.ForeignKey(blank=True, help_text='Nome do cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EMPRESTADA', 'Emprestada'), ('DEVOLVIDA', 'Devolvida'), ('PERDIDA', 'Perdida')], default='EMPRESTADA', help_text='Status do item no empréstimo', max_length=20, verbose_name='Status')),
                ('multa', models.FloatField(default=0, help_text='Multa por atraso deste item', verbose_name='Multa')),
                ('valor_restituicao_cobrado', models.FloatField(default=0, help_text='Se chave foi perdida, valor cobrado', verbose_name='Valor Restituicão Cobrado')),
                ('data_devolucao_item', models.DateField(blank=True, help_text='Data em que este item foi devolvido', null=True, verbose_name='Data de Devolução do Item')),
                ('copia_chave', models.ForeignKey(help_text='Cópia de chave emprestada', on_delete=django.db.models.deletion.PROTECT, related_name='itens_emprestimo', to='chaves.copiachave', verbose_name='Cópia de Chave')),
                ('emprestimo', models.ForeignKey(help_text='Empréstimo relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='emprestimos.emprestimo', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Item Empréstimo',
                'verbose_name_plural': 'Itens Empréstimos',
                'unique_together': {('emprestimo', 'copia_chave')},
            },
        ),
    ]
