# Generated by Django 6.0.3 on 2026-04-30 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_chave_propriedade_copiachave_chave'),
        ('clientes', '0002_cliente_foto_alter_cliente_email'),
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Nome do cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='copia',
            field=models.ForeignKey(blank=True, help_text='Cópia de chave relacionada', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='chaves.copiachave', verbose_name='Cópia'),
        ),
    ]
