# Generated by Django 4.2.30 on 2026-05-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_devolucao',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o empréstimo está em andamento ou concluído', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='valor_restituicao_cobrado',
            field=models.FloatField(default=0, help_text='Se chave foi perdida, valor cobrado', verbose_name='Valor Restituição Cobrado'),
        ),
    ]
