# Generated by Django 6.0.3 on 2026-07-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itememprestimo',
            name='data_devolucao_item',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='multa',
            field=models.FloatField(default=0),
        ),
    ]
