# Generated by Django 6.0.3 on 2026-07-03 20:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_itememprestimo_data_devolucao_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-id'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o empréstimo foi cancelado', null=True, verbose_name='Data e Hora de Cancelamento'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_notificacao_atraso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação de Atraso'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, help_text='Motivo do cancelamento do empréstimo', null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='tolerancia_minutos',
            field=models.PositiveIntegerField(default=15, help_text='Tempo de tolerância antes de começar a contar multa', verbose_name='Tolerância em Minutos'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='valor_multa_por_hora',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Valor cobrado por hora de atraso', max_digits=8, verbose_name='Valor da Multa por Hora'),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='data_perda_item',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Perda'),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='itememprestimo',
            name='valor_cobranca_perda',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Valor de Cobrança por Perda'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o empréstimo foi concluído', null=True, verbose_name='Data e Hora de Conclusão'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateTimeField(help_text='Data e hora prevista de devolução', verbose_name='Data e Hora Prevista'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateTimeField(help_text='Data e hora da retirada do empréstimo', verbose_name='Data e Hora de Retirada'),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='data_devolucao_item',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Devolução do Item'),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Multa'),
        ),
    ]
