# Generated by Django 4.2.30 on 2026-05-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_remove_emprestimo_data_devolucao_emprestimo_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itememprestimo',
            name='valor_restituicao_cobrado',
        ),
    ]
