# Generated by Django 6.0.3 on 2026-04-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_emprestimo_cliente_emprestimo_copia'),
        ('propriedades', '0002_propriedade_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='propriedade',
            field=models.ForeignKey(blank=True, help_text='Propriedade do empréstimo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='propriedades.propriedade', verbose_name='Propriedade'),
        ),
    ]
