# Generated by Django 4.2.30 on 2026-05-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_remove_itememprestimo_valor_restituicao_cobrado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itememprestimo',
            options={'permissions': (('view_item_emprestimo', 'Pode visualizar itens de empréstimo'),), 'verbose_name': 'Item Empréstimo', 'verbose_name_plural': 'Itens Empréstimos'},
        ),
    ]
