# Generated by Django 6.0.3 on 2026-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_itememprestimo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='notificado_atraso_email',
            field=models.BooleanField(default=False, editable=False, help_text='Indica se o aviso de atraso já foi enviado', verbose_name='Notificado por e-mail de atraso'),
        ),
    ]
