# Generated by Django 6.0.3 on 2026-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_emprestimo_notificado_atraso_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='notificado_atraso_email',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_conclusao',
            field=models.DateField(blank=True, help_text='Data em que o empréstimo foi concluído', null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o empréstimo está em andamento', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='itememprestimo',
            name='multa',
            field=models.FloatField(default=0, help_text='Multa final deste item', verbose_name='Multa'),
        ),
    ]
