# Generated by Django 6.0.3 on 2026-06-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0006_remove_emprestimo_notificado_atraso_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='notificacao_atraso',
            field=models.BooleanField(default=False, verbose_name='Notificação de Atraso Enviada'),
        ),
    ]
