# Generated by Django 6.0.3 on 2026-07-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data de início da reserva', verbose_name='Data Início')),
                ('data_fim', models.DateField(help_text='Data de término da reserva', verbose_name='Data Fim')),
                ('status', models.CharField(help_text='Status da reserva', max_length=50, verbose_name='Status')),
                ('chaves', models.ManyToManyField(help_text='Chaves da reserva', related_name='reservas', to='chaves.chave', verbose_name='Chaves')),
                ('cliente', models.ForeignKey(blank=True, help_text='Nome do cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
