# Generated by Django 6.0.3 on 2026-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data de início da reserva', verbose_name='Data Início')),
                ('data_fim', models.DateField(help_text='Data de término da reserva', verbose_name='Data Fim')),
                ('status', models.CharField(help_text='Status da reserva', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
