# Generated by Django 6.0.3 on 2026-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data_inicio', '-id'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações internas sobre a reserva', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', help_text='Status da reserva', max_length=50, verbose_name='Status'),
        ),
    ]
