# Generated by Django 6.0.3 on 2026-04-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0002_propriedade_tipo'),
        ('reservas', '0002_reserva_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='propriedade',
            field=models.ForeignKey(blank=True, help_text='Propriedade da reserva', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='propriedades.propriedade', verbose_name='Propriedade'),
        ),
    ]
