# Generated by Django 6.0.3 on 2026-07-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_options_and_more'),
        ('reservas', '0002_alter_reserva_options_reserva_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='emprestimo_gerado',
            field=models.ForeignKey(blank=True, help_text='Empréstimo criado a partir desta reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_origem', to='emprestimos.emprestimo', verbose_name='Empréstimo Gerado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_fim',
            field=models.DateTimeField(help_text='Data e hora de término da reserva', verbose_name='Data e Hora de Fim'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateTimeField(help_text='Data e hora de início da reserva', verbose_name='Data e Hora de Início'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada'), ('CONVERTIDA', 'Convertida em Empréstimo')], default='PENDENTE', help_text='Status da reserva', max_length=50, verbose_name='Status'),
        ),
    ]
