# Generated by Django 4.2.30 on 2026-06-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_remove_copiachave_valor_restituicao_alter_chave_id_and_more'),
        ('reservas', '0003_alter_reserva_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='chave',
        ),
        migrations.AddField(
            model_name='reserva',
            name='chaves',
            field=models.ManyToManyField(help_text='Chaves da reserva', related_name='reservas', to='chaves.chave', verbose_name='Chaves'),
        ),
    ]
